# A Long-Short Price & Volume Strategy

## Getting the data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
plt.style.use("seaborn")
warnings.filterwarnings("ignore")
import ta.trend as tat

In [2]:
data = pd.read_csv("bitcoin.csv", parse_dates = ["Date"], index_col = "Date")
data

                         Open      High       Low     Close       Volume
Date
2017-08-17 04:00:00   4261.48   4313.62   4261.32   4308.83    47.181009
2017-08-17 05:00:00   4308.83   4328.69   4291.37   4315.32    23.234916
2017-08-17 06:00:00   4330.29   4345.45   4309.37   4324.35     7.229691
2017-08-17 07:00:00   4316.62   4349.99   4287.41   4349.99     4.443249
2017-08-17 08:00:00   4333.32   4377.85   4333.32   4360.69     0.972807
...                       ...       ...       ...       ...          ...
2021-10-07 05:00:00  55073.20  55073.21  54545.07  54735.76  2251.122020
2021-10-07 06:00:00  54735.77  54968.06  54375.83  54534.16  1783.004260
2021-10-07 07:00:00  54534.16  54793.26  54235.33  54755.92  4163.431360
2021-10-07 08:00:00  54755.91  54778.91  54400.00  54538.30  2049.382180
2021-10-07 09:00:00  54538.31  54547.30  53786.13  53995.50  2739.153610

[36168 rows x 5 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 36168 entries, 2017-08-17 04:00:00 to 2021-10-07 09:00:00
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    36168 non-null  float64
 1   High    36168 non-null  float64
 2   Low     36168 non-null  float64
 3   Close   36168 non-null  float64
 4   Volume  36168 non-null  float64
dtypes: float64(5)
memory usage: 1.7 MB

In [4]:
data = data[["Close", "Volume"]].copy()

In [5]:
data["returns"] = np.log(data.Close.div(data.Close.shift(1)))
data["vol_ch"] = np.log(data.Volume.div(data.Volume.shift(1)))

In [6]:
data.loc[data.vol_ch > 3, "vol_ch"] = np.nan
data.loc[data.vol_ch < -3, "vol_ch"] = np.nan

In [7]:
data

                        Close       Volume   returns    vol_ch
Date
2017-08-17 04:00:00   4308.83    47.181009       NaN       NaN
2017-08-17 05:00:00   4315.32    23.234916  0.001505 -0.708335
2017-08-17 06:00:00   4324.35     7.229691  0.002090 -1.167460
2017-08-17 07:00:00   4349.99     4.443249  0.005912 -0.486810
2017-08-17 08:00:00   4360.69     0.972807  0.002457 -1.518955
...                       ...          ...       ...       ...
2021-10-07 05:00:00  54735.76  2251.122020 -0.006146  0.439863
2021-10-07 06:00:00  54534.16  1783.004260 -0.003690 -0.233129
2021-10-07 07:00:00  54755.92  4163.431360  0.004058  0.848040
2021-10-07 08:00:00  54538.30  2049.382180 -0.003982 -0.708801
2021-10-07 09:00:00  53995.50  2739.153610 -0.010002  0.290111

[36168 rows x 4 columns]

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 36168 entries, 2017-08-17 04:00:00 to 2021-10-07 09:00:00
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Close    36168 non-null  float64
 1   Volume   36168 non-null  float64
 2   returns  36167 non-null  float64
 3   vol_ch   36150 non-null  float64
dtypes: float64(4)
memory usage: 1.4 MB

## MMD calculate

In [8]:
data

                        Close       Volume   returns    vol_ch
Date
2017-08-17 04:00:00   4308.83    47.181009       NaN       NaN
2017-08-17 05:00:00   4315.32    23.234916  0.001505 -0.708335
2017-08-17 06:00:00   4324.35     7.229691  0.002090 -1.167460
2017-08-17 07:00:00   4349.99     4.443249  0.005912 -0.486810
2017-08-17 08:00:00   4360.69     0.972807  0.002457 -1.518955
...                       ...          ...       ...       ...
2021-10-07 05:00:00  54735.76  2251.122020 -0.006146  0.439863
2021-10-07 06:00:00  54534.16  1783.004260 -0.003690 -0.233129
2021-10-07 07:00:00  54755.92  4163.431360  0.004058  0.848040
2021-10-07 08:00:00  54538.30  2049.382180 -0.003982 -0.708801
2021-10-07 09:00:00  53995.50  2739.153610 -0.010002  0.290111

[36168 rows x 4 columns]

In [9]:
def crossCloudesMMD(data, ma1_name, ma2_name):
    sma1 = "sma_"+ma1_name
    sma2 = "sma_"+ma2_name
    ema1 = "ema_"+ma1_name
    ema2 = "ema_"+ma2_name
    cross_column_name="Cross"+ma1_name+ma2_name
    ma_VS_ma = ma1_name+"_VS_"+ma2_name

    data.dropna(subset=[sma1,ema1,sma2,ema2])
    ### conditional
    cond_over_now = ((data[sma1]>data[sma2]) & (data[sma1]>data[ema2]) & (data[ema1]>data[sma2]) & (data[ema1]>data[ema2]))
    cond_over_prev = ((data[sma1].shift(1)>data[sma2].shift(1)) & (data[sma1].shift(1)>data[ema2].shift(1)) & (data[ema1].shift(1)>data[sma2].shift(1)) & (data[ema1].shift(1)>data[ema2].shift(1)))
    cond_under_now = ((data[sma1]<data[sma2]) & (data[sma1]<data[ema2]) & (data[ema1]<data[sma2]) & (data[ema1]<data[ema2]))
    cond_under_prev = ((data[sma1].shift(1)<data[sma2].shift(1)) & (data[sma1].shift(1)<data[ema2].shift(1)) & (data[ema1].shift(1)<data[sma2].shift(1)) & (data[ema1].shift(1)<data[ema2].shift(1)))
    
    data[cross_column_name] = 0
    data.loc[cond_over_now & ~cond_over_prev, cross_column_name] = 1
    data.loc[cond_under_now & ~cond_under_prev, cross_column_name] = -1
    data[ma_VS_ma] = 0
    data.loc[cond_over_now, ma_VS_ma] = 1
    data.loc[cond_under_now, ma_VS_ma] = -1

def crossPriceMMD(data, ma_name):
    sma = "sma_"+ma_name
    ema = "ema_"+ma_name
    cross_column_name = "CrossPrice_"+ma_name
    data.dropna(subset=[ema,sma])
    
    #conditions
    cond_price_over_now = (data["Close"]>data[sma] & data["Close"]> data[ema])
    cond_price_over_prev = (data["Close"].shift(1)>data[sma].shift(1) & data["Close"].shift(1)> data[ema].shift(1))
    cond_price_under_now 
    cond_price_under_orev
    
    
    
    
    data[cross_column_name] = 0
    
    
    
    
def MMDCalculate(data, parameters):
    names=["Fast","Short","Mid","Long","Longest"]
    for i in range(0, len(parameters)):
        data["sma_"+names[i]]= tat.SMAIndicator(data["Close"],parameters[i]).sma_indicator()
        data["ema_"+names[i]]= tat.EMAIndicator(data["Close"],parameters[i]).ema_indicator()
    crossCloudesMMD(data, "Fast","Short")
    crossCloudesMMD(data, "Short", "Mid")
    crossCloudesMMD(data, "Fast", "Mid")
    
######  conditional for cross cloudes

#data.dropna
#cond1 = np.where( (data["ema_fast"]>data["ema_short"]) & (data["sma_fast"]>data["sma_short"] ) &False,0,1)
#cond1
#data.loc

In [14]:
testd = pd.read_csv("../data/testMMD.csv")


testd

   ema_fast  sma_fast  ema_short  sma_short
0      78.0      88.0         12         65
1      10.0      11.0          1          2
2      10.0      11.0          1          2
3       NaN       NaN         13         15
4      12.0      15.0         16         23

In [12]:
MMDCalculate(data, [12,48,288,1440])
data.to_excel("mmd.xlsx")

In [13]:
data[data["CrossFastMid"]==1]

,Close,Volume,returns,vol_ch,sma_Fast,ema_Fast,sma_Short,ema_Short,sma_Mid,ema_Mid,sma_Long,ema_Long,CrossFastShort,Fast_VS_Short,CrossShortMid,Short_VS_Mid,CrossFastMid,Fast_VS_Mid
Date,,,,,,,,,,,,,,,,,,
2017-08-29 03:00:00,4376.99,21.205700,0.014315,0.212474,4338.027500,4336.787635,4308.331667,4310.320992,4186.839861,4235.936773,NaN,NaN,0,1,1,1,1,1
2017-09-06 10:00:00,4525.39,22.478306,0.007259,-0.499123,4447.532500,4444.241735,4227.327500,4335.408785,4437.533715,4393.745908,NaN,NaN,0,1,0,-1,1,1
2017-09-20 16:00:00,4016.98,19.778717,0.002987,0.072881,3948.567500,3959.038387,3941.500000,3916.556531,3918.435729,3938.038959,NaN,NaN,1,1,0,0,1,1
2017-09-25 17:00:00,3892.31,21.030755,-0.004535,-0.889269,3822.931667,3835.110543,3735.002917,3753.050323,3731.881007,3817.901295,NaN,NaN,0,1,0,0,1,1
2017-10-26 11:00:00,5853.99,73.184051,0.019495,0.401938,5715.155000,5712.031361,5582.901875,5644.426913,5706.573160,5592.108941,4553.975674,4784.276707,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-19 22:00:00,46804.84,1421.326508,0.004236,0.282442,45801.110833,45998.428238,45163.035000,45444.920138,45690.680868,44928.466655,37096.538736,40108.359071,0,1,0,0,1,1
2021-08-27 17:00:00,48168.58,996.748140,-0.000215,-0.420892,47600.229167,47700.709129,47534.333750,47593.872747,47544.080521,47377.469820,39086.979993,42012.082941,1,1,0,0,1,1
2021-09-02 01:00:00,49708.13,4553.077869,0.018742,0.769264,48430.959167,48518.612018,47589.873958,47892.525902,48375.582292,47770.693588,40312.794382,43008.501301,0,1,0,0,1,1
2021-09-15 17:00:00,47980.67,1628.477550,-0.001579,-0.386620,47562.339167,47647.396473,46436.123958,46705.685023,47550.588438,46918.305358,43610.786625,44684.011615,0,1,0,-1,1,1
2021-10-01 04:00:00,43625.02,982.325550,-0.000247,-0.010929,43640.952500,43555.173274,42757.715000,42990.458754,43323.794271,43554.690058,45856.136444,44434.871057,0,1,0,-1,1,1

In [17]:
test = pd.DataFrame({"id":range(1,11)})
test["shift1"]=test["id"].shift(1)
test["shift-1"]=test["id"].shift(-1)
test

   id  shift1  shift-1
0   1     NaN      2.0
1   2     1.0      3.0
2   3     2.0      4.0
3   4     3.0      5.0
4   5     4.0      6.0
5   6     5.0      7.0
6   7     6.0      8.0
7   8     7.0      9.0
8   9     8.0     10.0
9  10     9.0      NaN

## Formulating a Long-Short Price/Volume Trading Strategy

In [18]:
data

,Close,Volume,returns,vol_ch,sma_Fast,ema_Fast,sma_Short,ema_Short,sma_Mid,ema_Mid,sma_Long,ema_Long,CrossFastShort,Fast_VS_Short,CrossShortMid,Short_VS_Mid,CrossFastMid,Fast_VS_Mid
Date,,,,,,,,,,,,,,,,,,
2017-08-17 04:00:00,4308.83,47.181009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0
2017-08-17 05:00:00,4315.32,23.234916,0.001505,-0.708335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0
2017-08-17 06:00:00,4324.35,7.229691,0.002090,-1.167460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0
2017-08-17 07:00:00,4349.99,4.443249,0.005912,-0.486810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0
2017-08-17 08:00:00,4360.69,0.972807,0.002457,-1.518955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-07 05:00:00,54735.76,2251.122020,-0.006146,0.439863,54942.398333,54701.091328,52230.423958,52612.836063,46017.234549,47615.731734,46773.706021,45345.232549,0,1,0,1,0,1
2021-10-07 06:00:00,54534.16,1783.004260,-0.003690,-0.233129,54942.926667,54675.409585,52339.553958,52691.257448,46058.349653,47663.610131,46780.622917,45357.986092,0,1,0,1,0,1
2021-10-07 07:00:00,54755.92,4163.431360,0.004058,0.848040,54918.420833,54687.795803,52449.541667,52775.529389,46101.091979,47712.691860,46788.020875,45371.029720,0,1,0,1,0,1
2021-10-07 08:00:00,54538.30,2049.382180,-0.003982,-0.708801,54886.759167,54664.796448,52545.756458,52847.479210,46142.042014,47759.927902,46795.391236,45383.753204,0,1,0,1,0,1
2021-10-07 09:00:00,53995.50,2739.153610,-0.010002,0.290111,54796.770000,54561.827764,52623.384583,52894.337201,46182.401319,47803.080650,46802.108653,45395.705663,0,1,0,1,0,1

In [19]:
data["position"] = 0 # Trading position -> Neutral for all bars
data

,Close,Volume,returns,vol_ch,sma_Fast,ema_Fast,sma_Short,ema_Short,sma_Mid,ema_Mid,sma_Long,ema_Long,CrossFastShort,Fast_VS_Short,CrossShortMid,Short_VS_Mid,CrossFastMid,Fast_VS_Mid,position
Date,,,,,,,,,,,,,,,,,,,
2017-08-17 04:00:00,4308.83,47.181009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
2017-08-17 05:00:00,4315.32,23.234916,0.001505,-0.708335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
2017-08-17 06:00:00,4324.35,7.229691,0.002090,-1.167460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
2017-08-17 07:00:00,4349.99,4.443249,0.005912,-0.486810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
2017-08-17 08:00:00,4360.69,0.972807,0.002457,-1.518955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-07 05:00:00,54735.76,2251.122020,-0.006146,0.439863,54942.398333,54701.091328,52230.423958,52612.836063,46017.234549,47615.731734,46773.706021,45345.232549,0,1,0,1,0,1,0
2021-10-07 06:00:00,54534.16,1783.004260,-0.003690,-0.233129,54942.926667,54675.409585,52339.553958,52691.257448,46058.349653,47663.610131,46780.622917,45357.986092,0,1,0,1,0,1,0
2021-10-07 07:00:00,54755.92,4163.431360,0.004058,0.848040,54918.420833,54687.795803,52449.541667,52775.529389,46101.091979,47712.691860,46788.020875,45371.029720,0,1,0,1,0,1,0
2021-10-07 08:00:00,54538.30,2049.382180,-0.003982,-0.708801,54886.759167,54664.796448,52545.756458,52847.479210,46142.042014,47759.927902,46795.391236,45383.753204,0,1,0,1,0,1,0
2021-10-07 09:00:00,53995.50,2739.153610,-0.010002,0.290111,54796.770000,54561.827764,52623.384583,52894.337201,46182.401319,47803.080650,46802.108653,45395.705663,0,1,0,1,0,1,0

__Buy and go Long (position = 1) if most recent returns are highly negative (cond1) and trading volume decreased (cond2)__

In [ ]:
# getting returns threshold for highly negative returns (<= 10th percentile)
return_thresh = np.percentile(data.returns.dropna(), 10)
return_thresh

In [ ]:
cond1 = data.returns <= return_thresh
cond1

In [ ]:
# getting vol_ch thresholds for (moderate) Volume Decreases (between 5th and 20th percentile)
volume_thresh = np.percentile(data.vol_ch.dropna(), [0, 20])
volume_thresh

In [ ]:
cond2 = data.vol_ch.between(volume_thresh[0], volume_thresh[1])
cond2

In [ ]:
data.loc[cond1 & cond2, "position"] = 1

__Sell and go Short (position = -1) if most recent returns are highly positive (cond3) and trading volume decreased (cond2)__

In [ ]:
# getting returns threshold for highly positve returns (>= 90th percentile)
return_thresh = np.percentile(data.returns.dropna(), 90)
return_thresh

In [ ]:
cond3 = data.returns >= return_thresh
cond3

In [ ]:
data.loc[cond3 & cond2, "position"] = -1

In [ ]:
data.position.value_counts()

In [ ]:
data.loc["12-2019", "position"].plot(figsize = (12, 8))
plt.show()

## A Long-Short Backtester Class

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from itertools import product
import warnings
warnings.filterwarnings("ignore")
plt.style.use("seaborn")

Major adjustments: 
- Different Strategy Definition with Short Positions (see method prepare_data)
- Four Strategy Parameters (instead of three)

In [ ]:
class Long_Short_Backtester():
    ''' Class for the vectorized backtesting of simple Long-Short trading strategies.
    
    Attributes
    ============
    filepath: str
        local filepath of the dataset (csv-file)
    symbol: str
        ticker symbol (instrument) to be backtested
    start: str
        start date for data import
    end: str
        end date for data import
    tc: float
        proportional trading costs per trade
    
    
    Methods
    =======
    get_data:
        imports the data.
        
    test_strategy:
        prepares the data and backtests the trading strategy incl. reporting (wrapper).
        
    prepare_data:
        prepares the data for backtesting.
    
    run_backtest:
        runs the strategy backtest.
        
    plot_results:
        plots the cumulative performance of the trading strategy compared to buy-and-hold.
        
    optimize_strategy:
        backtests strategy for different parameter values incl. optimization and reporting (wrapper).
    
    find_best_strategy:
        finds the optimal strategy (global maximum).
         
        
    print_performance:
        calculates and prints various performance metrics.
        
    '''    
    
    def __init__(self, filepath, symbol, start, end, tc):
        
        self.filepath = filepath
        self.symbol = symbol
        self.start = start
        self.end = end
        self.tc = tc
        self.results = None
        self.get_data()
        self.tp_year = (self.data.Close.count() / ((self.data.index[-1] - self.data.index[0]).days / 365.25))
        
    def __repr__(self):
        return "Long_Short_Backtester(symbol = {}, start = {}, end = {})".format(self.symbol, self.start, self.end)
        
    def get_data(self):
        ''' Imports the data.
        '''
        raw = pd.read_csv(self.filepath, parse_dates = ["Date"], index_col = "Date")
        raw = raw.loc[self.start:self.end].copy()
        raw["returns"] = np.log(raw.Close / raw.Close.shift(1))
        self.data = raw
        
    def test_strategy(self, percentiles = None, thresh = None):
        '''
        Prepares the data and backtests the trading strategy incl. reporting (Wrapper).
         
        Parameters
        ============
        percentiles: tuple (return_low_perc, return_high_perc, vol_low_perc, vol_high_perc)
            return and volume percentiles to be considered for the strategy.
            
        thresh: tuple (return_low_thresh, return_high_thresh, vol_low_thresh, vol_high_thesh)
            return and volume thresholds to be considered for the strategy.
        '''
        
        self.prepare_data(percentiles = percentiles, thresh = thresh)
        self.run_backtest()
        
        data = self.results.copy()
        data["creturns"] = data["returns"].cumsum().apply(np.exp)
        data["cstrategy"] = data["strategy"].cumsum().apply(np.exp)
        self.results = data
        
        self.print_performance()
    
    def prepare_data(self, percentiles, thresh):
        ''' Prepares the Data for Backtesting.
        '''
        ########################## Strategy-Specific #############################
        
        data = self.data[["Close", "Volume", "returns"]].copy()
        data["vol_ch"] = np.log(data.Volume.div(data.Volume.shift(1)))
        data.loc[data.vol_ch > 3, "vol_ch"] = np.nan
        data.loc[data.vol_ch < -3, "vol_ch"] = np.nan        
        
        if percentiles:
            self.return_thresh = np.percentile(data.returns.dropna(), [percentiles[0], percentiles[1]])
            self.volume_thresh = np.percentile(data.vol_ch.dropna(), [percentiles[2], percentiles[3]])
        elif thresh:
            self.return_thresh = [thresh[0], thresh[1]]
            self.volume_thresh = [thresh[2], thresh[3]]
                
        cond1 = data.returns <= self.return_thresh[0]
        cond2 = data.vol_ch.between(self.volume_thresh[0], self.volume_thresh[1])
        cond3 = data.returns >= self.return_thresh[1]
        
        data["position"] = 0
        data.loc[cond1 & cond2, "position"] = 1
        data.loc[cond3 & cond2, "position"] = -1

        ##########################################################################
        
        self.results = data
    
    def run_backtest(self):
        ''' Runs the strategy backtest.
        '''
        
        data = self.results.copy()
        data["strategy"] = data["position"].shift(1) * data["returns"]
        data["trades"] = data.position.diff().fillna(0).abs()
        data.strategy = data.strategy + data.trades * self.tc
        
        self.results = data
    
    def plot_results(self):
        '''  Plots the cumulative performance of the trading strategy compared to buy-and-hold.
        '''
        if self.results is None:
            print("Run test_strategy() first.")
        else:
            title = "{} | TC = {}".format(self.symbol, self.tc)
            self.results[["creturns", "cstrategy"]].plot(title=title, figsize=(12, 8))
            
    def optimize_strategy(self, return_low_range, return_high_range, vol_low_range, vol_high_range, metric = "Multiple"):
        '''
        Backtests strategy for different parameter values incl. Optimization and Reporting (Wrapper).
         
        Parameters
        ============
        return_low_range: tuple
            tuples of the form (start, end, step size).
        
        return_high_range: tuple
            tuples of the form (start, end, step size).
            
        vol_low_range: tuple
            tuples of the form (start, end, step size).
        
        vol_high_range: tuple
            tuples of the form (start, end, step size).
        
        metric: str
            performance metric to be optimized (can be "Multiple" or "Sharpe")
        '''
        
        self.metric = metric
        
        if metric == "Multiple":
            performance_function = self.calculate_multiple
        elif metric == "Sharpe":
            performance_function = self.calculate_sharpe
        
        return_low_range = range(*return_low_range)
        return_high_range = range(*return_high_range)
        vol_low_range = range(*vol_low_range)
        vol_high_range = range(*vol_high_range)
        
        combinations = list(product(return_low_range, return_high_range, vol_low_range, vol_high_range))
         
        performance = []
        for comb in combinations:
            self.prepare_data(percentiles = comb, thresh = None)
            self.run_backtest()
            performance.append(performance_function(self.results.strategy))
    
        self.results_overview =  pd.DataFrame(data = np.array(combinations), columns = ["return_low", "return_high", "vol_low", "vol_high"])
        self.results_overview["performance"] = performance
        self.find_best_strategy()
        
        
    def find_best_strategy(self):
        ''' Finds the optimal strategy (global maximum).
        '''
        
        best = self.results_overview.nlargest(1, "performance")
        return_perc = [best.return_low.iloc[0], best.return_high.iloc[0]]
        vol_perc = [best.vol_low.iloc[0], best.vol_high.iloc[0]]
        perf = best.performance.iloc[0]
        print("Return_Perc: {} | Volume_Perc: {} | {}: {}".format(return_perc, vol_perc, self.metric, round(perf, 5)))  
        self.test_strategy(percentiles = (return_perc[0], return_perc[1], vol_perc[0], vol_perc[1]))
            
    ############################## Performance ######################################
    
    def print_performance(self):
        ''' Calculates and prints various Performance Metrics.
        '''
        
        data = self.results.copy()
        strategy_multiple = round(self.calculate_multiple(data.strategy), 6)
        bh_multiple =       round(self.calculate_multiple(data.returns), 6)
        outperf =           round(strategy_multiple - bh_multiple, 6)
        cagr =              round(self.calculate_cagr(data.strategy), 6)
        ann_mean =          round(self.calculate_annualized_mean(data.strategy), 6)
        ann_std =           round(self.calculate_annualized_std(data.strategy), 6)
        sharpe =            round(self.calculate_sharpe(data.strategy), 6)
       
        print(100 * "=")
        print("SIMPLE PRICE & VOLUME STRATEGY | INSTRUMENT = {} | THRESHOLDS = {}, {}".format(self.symbol, np.round(self.return_thresh, 5), np.round(self.volume_thresh, 5)))
        print(100 * "-")
        print("PERFORMANCE MEASURES:")
        print("\n")
        print("Multiple (Strategy):         {}".format(strategy_multiple))
        print("Multiple (Buy-and-Hold):     {}".format(bh_multiple))
        print(38 * "-")
        print("Out-/Underperformance:       {}".format(outperf))
        print("\n")
        print("CAGR:                        {}".format(cagr))
        print("Annualized Mean:             {}".format(ann_mean))
        print("Annualized Std:              {}".format(ann_std))
        print("Sharpe Ratio:                {}".format(sharpe))
        
        print(100 * "=")
        
    def calculate_multiple(self, series):
        return np.exp(series.sum())
    
    def calculate_cagr(self, series):
        return np.exp(series.sum())**(1/((series.index[-1] - series.index[0]).days / 365.25)) - 1
    
    def calculate_annualized_mean(self, series):
        return series.mean() * self.tp_year
    
    def calculate_annualized_std(self, series):
        return series.std() * np.sqrt(self.tp_year)
    
    def calculate_sharpe(self, series):
        if series.std() == 0:
            return np.nan
        else:
            return self.calculate_cagr(series) / self.calculate_annualized_std(series)

In [ ]:
filepath = "bitcoin.csv"
symbol = "BTCUSDT"
start = "2017-08-17"
end = "2021-10-07"
tc = -0.00085

In [ ]:
tester = Long_Short_Backtester(filepath = filepath, symbol = symbol,
                              start = start, end = end, tc = tc)

In [ ]:
tester

In [ ]:
tester.data

In [ ]:
tester.test_strategy(percentiles = (10, 90, 5, 20))

In [ ]:
tester.plot_results()

In [ ]:
tester.results.trades.value_counts()

In [ ]:
tester.optimize_strategy(return_low_range = (2, 20, 2),
                         return_high_range = (80, 98, 2), 
                         vol_low_range = (0, 18, 2), 
                         vol_high_range = (18, 40, 2),
                         metric = "Sharpe")

In [ ]:
tester.plot_results()

In [ ]:
tester.results.cstrategy.plot(figsize = (12,8))
plt.show()

In [ ]:
tester.results.position.value_counts()

In [ ]:
tester.results.trades.value_counts()

In [ ]:
tester.optimize_strategy(return_low_range = (2, 7, 1),
                         return_high_range = (89, 99, 1), 
                         vol_low_range = (8, 14, 1), 
                         vol_high_range = (14, 22, 1),
                         metric = "Sharpe")

## A Long-Short Trader Class

_Disclaimer: <br>
The following illustrative examples are for general information and educational purposes only. <br>
It is neither investment advice nor a recommendation to trade, invest or take whatsoever actions.<br>
The below code should only be used in combination with the Binance Spot Testnet and NOT with a Live Trading Account._

In [ ]:
from binance.client import Client
from binance import ThreadedWebsocketManager
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import time

In [ ]:
class LongShortTrader():
    
    def __init__(self, symbol, bar_length, return_thresh, volume_thresh, units, position = 0):
        
        self.symbol = symbol
        self.bar_length = bar_length
        self.available_intervals = ["1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "8h", "12h", "1d", "3d", "1w", "1M"]
        self.units = units
        self.position = position
        self.trades = 0 
        self.trade_values = []
        
        #*****************add strategy-specific attributes here******************
        self.return_thresh = return_thresh
        self.volume_thresh = volume_thresh
        #************************************************************************
    
    def start_trading(self, historical_days):
        
        self.twm = ThreadedWebsocketManager()
        self.twm.start()
        
        if self.bar_length in self.available_intervals:
            self.get_most_recent(symbol = self.symbol, interval = self.bar_length,
                                 days = historical_days)
            self.twm.start_kline_socket(callback = self.stream_candles,
                                        symbol = self.symbol, interval = self.bar_length)
        # "else" to be added later in the course 
    
    def get_most_recent(self, symbol, interval, days):
    
        now = datetime.utcnow()
        past = str(now - timedelta(days = days))
    
        bars = client.get_historical_klines(symbol = symbol, interval = interval,
                                            start_str = past, end_str = None, limit = 1000)
        df = pd.DataFrame(bars)
        df["Date"] = pd.to_datetime(df.iloc[:,0], unit = "ms")
        df.columns = ["Open Time", "Open", "High", "Low", "Close", "Volume",
                      "Clos Time", "Quote Asset Volume", "Number of Trades",
                      "Taker Buy Base Asset Volume", "Taker Buy Quote Asset Volume", "Ignore", "Date"]
        df = df[["Date", "Open", "High", "Low", "Close", "Volume"]].copy()
        df.set_index("Date", inplace = True)
        for column in df.columns:
            df[column] = pd.to_numeric(df[column], errors = "coerce")
        df["Complete"] = [True for row in range(len(df)-1)] + [False]
        
        self.data = df
    
    def stream_candles(self, msg):
        
        # extract the required items from msg
        event_time = pd.to_datetime(msg["E"], unit = "ms")
        start_time = pd.to_datetime(msg["k"]["t"], unit = "ms")
        first   = float(msg["k"]["o"])
        high    = float(msg["k"]["h"])
        low     = float(msg["k"]["l"])
        close   = float(msg["k"]["c"])
        volume  = float(msg["k"]["v"])
        complete=       msg["k"]["x"]
        
        # stop trading session
        if self.trades >= 50: # stop stream after 5 trades
            self.twm.stop()
            if self.position == 1:
                order = client.create_order(symbol = self.symbol, side = "SELL", type = "MARKET", quantity = self.units)
                self.report_trade(order, "GOING NEUTRAL AND STOP")
                self.position = 0
            elif self.position == -1:
                order = client.create_order(symbol = self.symbol, side = "BUY", type = "MARKET", quantity = self.units)
                self.report_trade(order, "GOING NEUTRAL AND STOP")
                self.position = 0
            else: 
                print("STOP")
    
        # print out
        print(".", end = "", flush = True) # just print something to get a feedback (everything OK) 
    
        # feed df (add new bar / update latest bar)
        self.data.loc[start_time] = [first, high, low, close, volume, complete]
        
        # prepare features and define strategy/trading positions whenever the latest bar is complete
        if complete == True:
            self.define_strategy()
            self.execute_trades()
        
    def define_strategy(self):
        
        df = self.data.copy()
        
        #******************** define your strategy here ************************
        df = df[["Close", "Volume"]].copy()
        df["returns"] = np.log(df.Close / df.Close.shift())
        df["vol_ch"] = np.log(df.Volume.div(df.Volume.shift(1)))
        df.loc[df.vol_ch > 3, "vol_ch"] = np.nan
        df.loc[df.vol_ch < -3, "vol_ch"] = np.nan  
        
        cond1 = df.returns <= self.return_thresh[0]
        cond2 = df.vol_ch.between(self.volume_thresh[0], self.volume_thresh[1])
        cond3 = df.returns >= self.return_thresh[1]
        
        df["position"] = 0
        df.loc[cond1 & cond2, "position"] = 1
        df.loc[cond3 & cond2, "position"] = -1
        #***********************************************************************
        
        self.prepared_data = df.copy()
    
    def execute_trades(self): 
        if self.prepared_data["position"].iloc[-1] == 1: # if position is long -> go/stay long
            if self.position == 0:
                order = client.create_order(symbol = self.symbol, side = "BUY", type = "MARKET", quantity = self.units)
                self.report_trade(order, "GOING LONG")  
            elif self.position == -1:
                order = client.create_order(symbol = self.symbol, side = "BUY", type = "MARKET", quantity = self.units)
                self.report_trade(order, "GOING NEUTRAL")
                time.sleep(0.1)
                order = client.create_order(symbol = self.symbol, side = "BUY", type = "MARKET", quantity = self.units)
                self.report_trade(order, "GOING LONG")
            self.position = 1
        elif self.prepared_data["position"].iloc[-1] == 0: # if position is neutral -> go/stay neutral
            if self.position == 1:
                order = client.create_order(symbol = self.symbol, side = "SELL", type = "MARKET", quantity = self.units)
                self.report_trade(order, "GOING NEUTRAL") 
            elif self.position == -1:
                order = client.create_order(symbol = self.symbol, side = "BUY", type = "MARKET", quantity = self.units)
                self.report_trade(order, "GOING NEUTRAL") 
            self.position = 0
        if self.prepared_data["position"].iloc[-1] == -1: # if position is short -> go/stay short
            if self.position == 0:
                order = client.create_order(symbol = self.symbol, side = "SELL", type = "MARKET", quantity = self.units)
                self.report_trade(order, "GOING SHORT") 
            elif self.position == 1:
                order = client.create_order(symbol = self.symbol, side = "SELL", type = "MARKET", quantity = self.units)
                self.report_trade(order, "GOING NEUTRAL")
                time.sleep(0.1)
                order = client.create_order(symbol = self.symbol, side = "SELL", type = "MARKET", quantity = self.units)
                self.report_trade(order, "GOING SHORT")
            self.position = -1
    
    def report_trade(self, order, going): 
        
        # extract data from order object
        side = order["side"]
        time = pd.to_datetime(order["transactTime"], unit = "ms")
        base_units = float(order["executedQty"])
        quote_units = float(order["cummulativeQuoteQty"])
        price = round(quote_units / base_units, 5)
        
        # calculate trading profits
        self.trades += 1
        if side == "BUY":
            self.trade_values.append(-quote_units)
        elif side == "SELL":
            self.trade_values.append(quote_units) 
        
        if self.trades % 2 == 0:
            real_profit = round(np.sum(self.trade_values[-2:]), 3) 
            self.cum_profits = round(np.sum(self.trade_values), 3)
        else: 
            real_profit = 0
            self.cum_profits = round(np.sum(self.trade_values[:-1]), 3)
        
        # print trade report
        print(2 * "\n" + 100* "-")
        print("{} | {}".format(time, going)) 
        print("{} | Base_Units = {} | Quote_Units = {} | Price = {} ".format(time, base_units, quote_units, price))
        print("{} | Profit = {} | CumProfits = {} ".format(time, real_profit, self.cum_profits))
        print(100 * "-" + "\n")

In [ ]:
api_key = "insert here"
secret_key = "insert here"
### BINANCE TESTNET
api_key = '7BZCD18RNJcGUPYTWJJF1okfpajZZUdIXxq12JyC69neYuDkK3jzigOUhKLxujLb'
secret_key = 'IsrLOOSAfKPA7ktaF9m4lHQntbSqYoHxcICieILM4r2BqWp2e1zI6XBjuB52suja'

In [ ]:
client = Client(api_key = api_key, api_secret = secret_key, tld = "com", testnet = True)

For illustration purposes: a very dynamic Strategy (parameters) with many trades:

In [ ]:
symbol = "BTCBUSD"
bar_length = "1m"
return_thresh = [-0.0001, 0.0001]
volume_thresh = [-3, 3]
units = 0.01
position = 0

In [ ]:
client.get_account()

In [ ]:
trader = LongShortTrader(symbol = symbol, bar_length = bar_length, return_thresh = return_thresh,
                        volume_thresh = volume_thresh, units = units, position = position)

In [ ]:
trader.start_trading(historical_days = 1/24)

In [ ]:
trader.prepared_data

In [ ]:
trader.cum_profits

In [ ]:
client.get_account()

In [ ]:
trader.trade_values